definitions:
  presenter.AdviceList:
    properties:
      results:
        items:
          $ref: '#/definitions/presenter.AdviceResponse'
        type: array
      total:
        example: 1
        type: integer
    type: object
  presenter.AdvicePayload:
    properties:
      advice_date:
        example: 2021-10-24 15:04
        type: string
      classroom_id:
        example: 613aab578a6ef50007e622be
        type: string
      subject:
        example: Chemistry
        type: string
    type: object
  presenter.AdviceResponse:
    properties:
      advice_date:
        example: 2021-10-24 15:04
        type: string
      classroom:
        $ref: '#/definitions/presenter.ClassroomResponse'
      id:
        example: 613aab578a6ef50007e622be
        type: string
      students_will_attend:
        items:
          type: string
        type: array
      subject:
        example: Chemistry
        type: string
      user:
        $ref: '#/definitions/presenter.TinyUserResponse'
    type: object
  presenter.BasicUser:
    properties:
      email:
        example: sudo.von.contact@gmail.com
        type: string
      id:
        example: 613aab4d8a6ef50007e622bd
        type: string
      name:
        example: Sudo Von
        type: string
    type: object
  presenter.BatteryPayload:
    properties:
      battery_level:
        example: 20
        type: number
      battery_state:
        example: charging
        type: string
      low_power_mode:
        example: true
        type: boolean
    type: object
  presenter.ClassroomResponse:
    properties:
      id:
        example: 613aab578a6ef50007e622be
        type: string
      name:
        example: VoN
        type: string
    type: object
  presenter.ContactPayload:
    properties:
      contact_name:
        example: VoN
        type: string
      contact_number:
        example: "528661234567"
        type: string
      message:
        example: Hi, i need...
        type: string
    type: object
  presenter.ContactResponse:
    properties:
      contact_name:
        example: VoN
        type: string
      contact_number:
        example: "528661234567"
        type: string
      id:
        example: 613aab578a6ef50007e622be
        type: string
      message:
        example: Hi, i need...
        type: string
      user_id:
        example: 613aab578a6ef50007e622bd
        type: string
    type: object
  presenter.DepartmentList:
    properties:
      results:
        items:
          $ref: '#/definitions/presenter.DepartmentResponse'
        type: array
      total:
        example: 1
        type: integer
    type: object
  presenter.DepartmentPayload:
    properties:
      cost:
        example: 1000
        type: number
      description:
        example: description
        type: string
      neighborhood:
        example: neighborhood
        type: string
      street:
        example: street
        type: string
    type: object
  presenter.DepartmentResponse:
    properties:
      available:
        example: true
        type: boolean
      cost:
        example: 1000
        type: number
      description:
        example: description
        type: string
      id:
        example: 613aab578a6ef50007e622be
        type: string
      neighborhood:
        example: neighborhood
        type: string
      street:
        example: street
        type: string
      user:
        $ref: '#/definitions/presenter.BasicUser'
    type: object
  presenter.SuggestionPayload:
    properties:
      suggestion:
        example: I would like to...
        type: string
    type: object
  presenter.TinyUniversityList:
    properties:
      results:
        items:
          $ref: '#/definitions/presenter.TinyUniversityResponse'
        type: array
      total:
        example: 10
        type: integer
    type: object
  presenter.TinyUniversityResponse:
    properties:
      id:
        example: 613aab578a6ef50007e622be
        type: string
      name:
        example: VoN
        type: string
      profile_picture:
        example: Url
        type: string
    type: object
  presenter.TinyUserResponse:
    properties:
      birth_date:
        example: "1997-04-17"
        type: string
      email:
        example: sudo.von.contact@gmail.com
        type: string
      id:
        example: 613aab4d8a6ef50007e622bd
        type: string
      name:
        example: Sudo Von
        type: string
      registration_number:
        example: "16190770"
        type: string
    type: object
  presenter.UniversityResponse:
    properties:
      classrooms:
        items:
          $ref: '#/definitions/presenter.ClassroomResponse'
        type: array
      id:
        example: 613aab578a6ef50007e622be
        type: string
      name:
        example: VoN
        type: string
      profile_picture:
        example: Url
        type: string
    type: object
  presenter.UpdateAdvicePayload:
    properties:
      advice_date:
        example: 1997-04-17 15:04
        type: string
      classroom_id:
        example: 613aab578a6ef50007e622be
        type: string
      subject:
        example: Chemistry
        type: string
    type: object
  presenter.UpdateContactPayload:
    properties:
      contact_name:
        example: VoN
        type: string
      contact_number:
        example: "528661234567"
        type: string
      message:
        example: Hi, i need...
        type: string
    type: object
  presenter.UpdateDepartmentPayload:
    properties:
      available:
        example: true
        type: boolean
      cost:
        example: 1000
        type: number
      description:
        example: description
        type: string
      neighborhood:
        example: neighborhood
        type: string
      street:
        example: street
        type: string
    type: object
  presenter.UpdateUserPayload:
    properties:
      birth_date:
        example: "1997-04-17"
        type: string
      email:
        example: sudo.von.contact@gmail.com
        type: string
      name:
        example: Sudo Von
        type: string
      registration_number:
        example: "16190770"
        type: string
    type: object
  presenter.UserMoodPayload:
    properties:
      mood:
        example: 5
        type: number
    type: object
  presenter.UserMoodResponse:
    properties:
      creation_date:
        example: "2021-10-10"
        type: string
      id:
        example: 613aab578a6ef50007e622be
        type: string
      mood:
        example: 10
        type: number
      user_id:
        example: 613aab4d8a6ef50007e622bd
        type: string
    type: object
  presenter.UserPayload:
    properties:
      birth_date:
        example: "1997-04-17"
        type: string
      email:
        example: sudo.von.contact@gmail.com
        type: string
      name:
        example: Sudo Von
        type: string
      password:
        example: "123456"
        type: string
      registration_number:
        example: "16190770"
        type: string
      university_id:
        example: 61366c06d3f6379af212aeb5
        type: string
    type: object
info:
  contact: {}
paths:
  /advices:
    get:
      description: List advices.
      operationId: list-advices
      parameters:
      - description: User ID that will attend to the advice.
        in: path
        name: will_attend
        type: string
      - description: User ID that will teach the advice.
        in: path
        name: will_teach
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AdviceList'
      security:
      - BearerJWT: []
      summary: List advices.
      tags:
      - advices
    post:
      description: Create advice.
      operationId: create-advice
      parameters:
      - description: Advice that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.AdvicePayload'
      produces:
      - application/json
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create advice.
      tags:
      - advices
  /advices/{id}:
    delete:
      description: Delete advice given its ID.
      operationId: delete-advice
      parameters:
      - description: Advice ID.
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Delete advice.
      tags:
      - advices
    get:
      description: Get advice given its ID.
      operationId: get-advice-by-id
      parameters:
      - description: Advice ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AdviceResponse'
      security:
      - BearerJWT: []
      summary: Show advice.
      tags:
      - advices
    patch:
      description: Update advice given its ID.
      operationId: update-advice
      parameters:
      - description: Advice ID.
        in: path
        name: id
        required: true
        type: string
      - description: Advice information that wants to be updated.
        in: body
        name: updatePayload
        required: true
        schema:
          $ref: '#/definitions/presenter.UpdateAdvicePayload'
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Update advice.
      tags:
      - advices
  /advices/{id}/students-number:
    patch:
      description: Update the number of students who will attend the advice.
      operationId: update-advice-students-number
      parameters:
      - description: Advice ID.
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Update advice students number.
      tags:
      - advices
  /auth/login:
    post:
      description: Gets Bearer token.
      operationId: login
      responses:
        "200":
          description: ""
          headers:
            Access-Control-Allow-Headers:
              description: Authorization.
              type: string
            Authorization:
              description: Bearer jwt that must be used as Api Key in the Authorize
                section.
              type: string
      security:
      - BasicAuth: []
      summary: JWT.
      tags:
      - authentication
  /batteries:
    post:
      description: Create battery.
      operationId: create-battery
      parameters:
      - description: Battery info that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.BatteryPayload'
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create battery.
      tags:
      - batteries
  /contacts/{id}:
    patch:
      description: Update contact given its ID.
      operationId: update-contact-by-id
      parameters:
      - description: Contact ID.
        in: path
        name: id
        required: true
        type: string
      - description: Contact information that wants to be updated.
        in: body
        name: updatePayload
        required: true
        schema:
          $ref: '#/definitions/presenter.UpdateContactPayload'
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Update contact.
      tags:
      - contacts
  /contacts/users/{id}:
    get:
      description: Show contact given the user ID.
      operationId: show-contact-by-user-id
      parameters:
      - description: User ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.ContactResponse'
      security:
      - BearerJWT: []
      summary: Show contact by user ID.
      tags:
      - contacts
    post:
      description: Create contact for a specific user given its ID.
      operationId: create-contact-by-user-id
      parameters:
      - description: User ID.
        in: path
        name: id
        required: true
        type: string
      - description: Contact that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.ContactPayload'
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create contact.
      tags:
      - contacts
  /departments:
    get:
      description: List departments.
      operationId: list-departments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.DepartmentList'
      security:
      - BearerJWT: []
      summary: List departments.
      tags:
      - departments
    post:
      description: Create department.
      operationId: create-department
      parameters:
      - description: Department that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.DepartmentPayload'
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create department.
      tags:
      - departments
  /departments/{id}:
    delete:
      description: Delete department given its ID.
      operationId: delete-department
      parameters:
      - description: Department ID.
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Delete department.
      tags:
      - departments
    get:
      description: Get department given its ID.
      operationId: get-department-by-id
      parameters:
      - description: Department ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.DepartmentResponse'
      security:
      - BearerJWT: []
      summary: Show department.
      tags:
      - departments
    patch:
      description: Update department given its ID.
      operationId: update-department
      parameters:
      - description: Department ID.
        in: path
        name: id
        required: true
        type: string
      - description: Department information that wants to be updated.
        in: body
        name: updatePayload
        required: true
        schema:
          $ref: '#/definitions/presenter.UpdateDepartmentPayload'
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Update department.
      tags:
      - departments
  /suggestions:
    post:
      description: Create suggestion.
      operationId: create-suggestion
      parameters:
      - description: Suggestion that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.SuggestionPayload'
      produces:
      - application/json
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create suggestion.
      tags:
      - suggestions
  /universities:
    get:
      description: List basic universities information.
      operationId: list-universities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.TinyUniversityList'
      summary: List universities.
      tags:
      - universities
  /universities/{id}:
    get:
      description: Show basic university information.
      operationId: show-university
      parameters:
      - description: University ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.UniversityResponse'
      security:
      - BearerJWT: []
      summary: Show university.
      tags:
      - universities
  /users:
    post:
      description: Create user.
      operationId: create-user
      parameters:
      - description: User information that wants to be stored.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.UserPayload'
      responses:
        "201":
          description: ""
      summary: Create user.
      tags:
      - users
  /users-mood/{users}/{id}:
    post:
      description: Create user's mood for the current day given the user ID.
      operationId: create-user-mood
      parameters:
      - description: User ID.
        in: path
        name: id
        required: true
        type: string
      - description: User's mood for the current day.
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/presenter.UserMoodPayload'
      responses:
        "201":
          description: ""
      security:
      - BearerJWT: []
      summary: Create user's mood.
      tags:
      - users-mood
  /users-mood/users/{id}:
    get:
      description: Get user's mood for the current day given the user ID.
      operationId: get-user-mood-by-user-id
      parameters:
      - description: User ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.UserMoodResponse'
      security:
      - BearerJWT: []
      summary: Show user's mood.
      tags:
      - users-mood
  /users/{id}:
    get:
      description: Show basic user information.
      operationId: get-tiny-user
      parameters:
      - description: User ID.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.TinyUserResponse'
      security:
      - BearerJWT: []
      summary: Show user.
      tags:
      - users
    patch:
      description: Update user information.
      operationId: update-user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User information that wants to be updated.
        in: body
        name: updatePayload
        required: true
        schema:
          $ref: '#/definitions/presenter.UpdateUserPayload'
      responses:
        "200":
          description: ""
      security:
      - BearerJWT: []
      summary: Update user.
      tags:
      - users
swagger: "2.0"
